### ISSUE TITLE
游戏自启动问题

### ISSUE THREAD

**Issue by Crany-web** [Java-S12138/frank#107]
2023-1-7更新后使用Frank自动打开游戏必须要登录WeGame然后选区才能进游戏大厅，大家有没有办法绕开

**Comment by Java-S12138** [comment]
我之前是不用wegame就能登录, 但是后面也被强制使用了. 其实, 使用wegame作为登录器使用也还行, 不用输入密码, 直接选择大区就行了, 进入英雄联盟大厅后, 手动关闭wegame就好了
