### ISSUE TITLE
自动跳转赌博网站？？

### ISSUE THREAD

**Issue by ottocsb** [Java-S12138/frank#108]
最近几天发现打开cube后打开frank，到游戏大厅时会自动打开浏览器打开“雷竞技”的网赌网站，我不清楚是frank还是cube的问题，电脑的环境还是比较干净的，切只会出现在打开cube和frank登录游戏后的场景

**Comment by Java-S12138** [comment]
前天Cube平台被黑了
已经处理了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Java-S12138/frank"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月16日(星期一) 下午3:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Java-S12138/frank] 自动跳转赌博网站？？ (Issue #108)





 
最近几天发现打开cube后打开frank，到游戏大厅时会自动打开浏览器打开“雷竞技”的网赌网站，我不清楚是frank还是cube的问题，电脑的环境还是比较干净的，切只会出现在打开cube和frank登录游戏后的场景

**Comment by ottocsb** [comment]
thanks
