### ISSUE TITLE
您好，請問frank的1.3版本及以前版本是都用不了嗎？我不想下cube誒= =

### ISSUE THREAD

**Issue by whiteday13jin** [Java-S12138/frank#109]
謝謝你的軟件，很棒。如題

**Comment by Java-S12138** [comment]
不知道能不能用, 你可以去试试. 其实cube和frank都是用electron框架写的, 在内存方面其实不会增加太多.而且cube也提供了一些技术, 让frank功能更加完善

**Comment by LeeG4ng** [comment]
@Java-S12138 没有人会想多装一个软件的...

**Comment by Kaleo5533** [comment]
确实，附加到cube后就在没用过

**Comment by LvBay** [comment]
可以参考这个 https://github.com/Java-S12138/frank/issues/110#issuecomment-1438393324 @whiteday13jin
