### ISSUE TITLE
使用frankCube分支编译的frank，lol更新以后frank无法获取召唤师信息。通过netstat发现lcu接口超时，请问这种情况要怎么修复呢

### ISSUE THREAD

**Issue by LvBay** [Java-S12138/frank#110]

**Comment by Java-S12138** [comment]
去年国服lol12.18 更新后, 就有很长一段时间lcu接口不能正常使用, 后面cube平台找到我, 他们的平台底层可以解决这个问题, 这也是我入驻cube平台的重要原因之一

**Comment by LvBay** [comment]
cube平台太重了，不太想用。NPhoenix前两天貌似已经解决了这个问题，但开发者没理我～所以想问问你有没有什么思路

**Comment by Java-S12138** [comment]
那没办法了, 技术有限....没什么能帮到你的了

**Comment by LvBay** [comment]
我发现了一个解决方式：需要修改lol/TCLS目录下的wegame_launch.tmp文件LastLoginMethod=2改成LastLoginMethod=1，然后关闭WeGame，直接启动TCLS目录下的Client.exe。

可能是wegame做了什么操作把lcu端口禁了～

**Comment by whiteday13jin** [comment]
不止是国服，我玩台服有cube的时候也能用，没cube就不行。主要是用cube就掉帧，而且就开cube里的frank这一个插件，感觉真没必要就卸了。有点可惜

**Comment by xiaowuyaya** [comment]
> 去年国服lol12.18 更新后, 就有很长一段时间lcu接口不能正常使用, 后面cube平台找到我, 他们的平台底层可以解决这个问题, 这也是我入驻cube平台的重要原因之一

去年Cube联系我的时候 有说过他们是用注入式实现的，当时我并不知道注入式是什么意思，他们现在有换其他的方案吗？

**Comment by Java-S12138** [comment]
> > 去年国服lol12.18 更新后, 就有很长一段时间lcu接口不能正常使用, 后面cube平台找到我, 他们的平台底层可以解决这个问题, 这也是我入驻cube平台的重要原因之一
> 
> 去年Cube联系我的时候 有说过他们是用注入式实现的，当时我并不知道注入式是什么意思，他们现在有换其他的方案吗？

一直都是这个方案
