### ISSUE TITLE
请问下作者，frank是否可以查询隐藏战绩呢？如果可以的话，是否违反拳头的api使用公约呢

### ISSUE THREAD

**Issue by LvBay** [Java-S12138/frank#114]
拳头[api文档](https://developer.riotgames.com/docs/lol#developer-api-policy_game-integrity)描述的是：
`Products cannot identify or analyze players who are deliberately hidden by the game.`

在游戏里设定隐藏战绩的玩家，是否算是`deliberately hidden by the game`？

**Comment by Java-S12138** [comment]
﻿frank之前是可以查询查询战绩的，包括隐藏战绩的召唤师，后面被官方警告了，就下架了查询战绩的功能

**Comment by Java-S12138** [comment]
腾讯Sent from my iPhoneOn May 31, 2023, at 15:00, faker ***@***.***> wrote:﻿
@Java-S12138 官方是指拳头还是腾讯或者wegame？

**Comment by LvBay** [comment]
好的 谢谢啦
