### ISSUE TITLE
关于我每次大乱斗总有几个人获取不到数据导致我自己成了下等马这件事

### ISSUE THREAD

**Issue by watchingfun** [Java-S12138/frank#14]
如题

**Comment by Java-S12138** [comment]
> 如题

关于上等马的评判是由最近的10场排位,匹配模式进行分析了, 如果你的队友没有进行排位的话,数据就会为空

**Comment by TimothyChan44** [comment]
> > 如题
> 
> 关于上等马的评判是由最近的10场排位,匹配模式进行分析了, 如果你的队友没有进行排位的话,数据就会为空

如果查不到为空的话，我感觉可以给个“小黑马”的等级，下等马感觉不太好
