### ISSUE TITLE
你真棒！但是我想给你提工单

### ISSUE THREAD

**Issue by 1601565568** [Java-S12138/frank#17]
1. 我是卡拉曼达的，无法获取数据，只能本地，这个是核心功能 ，希望尽早维护好
2. 希望新增登录保存密码功能
3. 我能成为这个项目的维护者吗，我现在是一面前端，刚入职的程序员，
4. 加油！我很喜欢打游戏，第一次在b站看到真的眼前一亮，

**Comment by etoyz** [comment]
我也希望能成为这个项目的开发者，建议作者可以拉个群，方便大家一起交流 @Java-S12138
