### ISSUE TITLE
启动后获取不到游戏账户信息

### ISSUE THREAD

**Issue by tanghengvip** [Java-S12138/frank#39]
系统环境：WIN10 x64
Frank版本：1.15.1212（管理员权限运行）
复现概率：必现
截图：
![图片1](https://user-images.githubusercontent.com/4047349/179338682-b8827d52-d295-4371-b966-954d1fb52473.png)

![image](https://user-images.githubusercontent.com/4047349/180470956-e4a44073-9825-4dde-93c4-c69570a70e3e.png)

**Comment by new3Git** [comment]
刷新下

**Comment by tanghengvip** [comment]
![image](https://user-images.githubusercontent.com/4047349/180591310-804558dc-7d0e-43c1-9c8e-514f6c25140b.png)
使用1.17.1213版本仍然有此问题 @Java-S12138

**Comment by new3Git** [comment]
> 

![image](https://user-images.githubusercontent.com/93309258/180631596-71c3c623-104f-4589-864e-2b858e556f1e.png)
