### ISSUE TITLE
召唤师实力排行界面出现重复，其中一个可以正常关闭，另一个窗口关闭提示报错

### ISSUE THREAD

**Issue by lingzwang** [Java-S12138/frank#56]
![image](https://user-images.githubusercontent.com/42690430/183277321-43c453d4-345e-43db-88fc-864971217265.png)

**Comment by lingzwang** [comment]
版本v1.19.1214

**Comment by tanghengvip** [comment]
+1

**Comment by Java-S12138** [comment]
问题已经修复了, 下个版本就不会出现这样的问题了
