### ISSUE TITLE
[Feature Request] 希望加入退出客户端后同时关闭Frank的选项

### ISSUE THREAD

**Issue by Calvaire** [Java-S12138/frank#62]
有时候会单独关闭客户端，然后再想启动游戏的话就要重新点击Frank，这时之前打开的Frank尚未退出，就会同时存在两个，所以希望加入退出客户端后同时关闭Frank的选项

**Comment by Kejiboy** [comment]
这个功能倒是挺好的，不过实现有点麻烦
