### ISSUE TITLE
些许小建议

### ISSUE THREAD

**Issue by logan-yunlong** [Java-S12138/frank#7]
up主火了，没想到有这么多人同时在观看：
<img width="462" alt="image" src="https://user-images.githubusercontent.com/26224399/177693919-cb63d2fc-ffd3-4858-b8e2-6c97fd328b9c.png">

## 认真提建议：开发云顶之弈的棋子阵容和羁绊的建议
1. 在每次获取到海克斯科技的时候，可以自动显示对应的阵容推荐（例如dd街区适合:[星界龙/金鳞龙...]
2. 在D牌的时候，可以预先设置秒抢卡牌，（例如：我本局玩金鳞龙刺客，需要刺客+金鳞龙，可以帮我：秒选、高亮、或者禁用掉刷牌2S[目的是防止手贱刷过去]、甚至帮我秒选中）
3. 给出装备和成的建议和文档，只需要合成思路和文档即可，我是休闲娱乐玩家，偶尔玩一下，在玩的时候，经常不知道我需要饮血剑该怎么合成
4. 给出本人棋盘已有的战备席中的牌和装备（帮助我在选秀阶段不用切来切去）

本人也是vue+java+node 全栈开发，up主有兴趣可以一起来搞~  
![4a58ebde8fe3db0cf425e1132810a592](https://user-images.githubusercontent.com/26224399/177694725-3755eb45-9730-4b99-9c9b-8abf1492a3a3.jpg)

**Comment by Zaiy18** [comment]
期待

**Comment by dannyXSC** [comment]
> up主火了，没想到有这么多人同时在观看： <img alt="image" width="462" src="https://user-images.githubusercontent.com/26224399/177693919-cb63d2fc-ffd3-4858-b8e2-6c97fd328b9c.png">
> 
> ## 认真提建议：开发云顶之弈的棋子阵容和羁绊的建议
> 1. 在每次获取到海克斯科技的时候，可以自动显示对应的阵容推荐（例如dd街区适合:[星界龙/金鳞龙...]
> 2. 在D牌的时候，可以预先设置秒抢卡牌，（例如：我本局玩金鳞龙刺客，需要刺客+金鳞龙，可以帮我：秒选、高亮、或者禁用掉刷牌2S[目的是防止手贱刷过去]、甚至帮我秒选中）
> 3. 给出装备和成的建议和文档，只需要合成思路和文档即可，我是休闲娱乐玩家，偶尔玩一下，在玩的时候，经常不知道我需要饮血剑该怎么合成
> 4. 给出本人棋盘已有的战备席中的牌和装备（帮助我在选秀阶段不用切来切去）
> 
> 本人也是vue+java+node 全栈开发，up主有兴趣可以一起来搞~ ![4a58ebde8fe3db0cf425e1132810a592](https://user-images.githubusercontent.com/26224399/177694725-3755eb45-9730-4b99-9c9b-8abf1492a3a3.jpg)

我之前做过这个事情，但是卡片信息的api，拳头和腾讯都没有放开。我之前是通过机器学习来识别每一张图片的，但是太麻烦就没有维护了

**Comment by logan-yunlong** [comment]
> 

想法不谋而合，我也预期使用机器学习来识别卡牌，主要是协助玩家做出一些决策，不应该主动调用牌库和其他阵容的API
