### ISSUE TITLE
请教2个项目问题

### ISSUE THREAD

**Issue by OrpheusQ** [Java-S12138/frank#72]
1.自测发现不论是通过up提供的vscode命令启动，还是使用编译成功的版本，如果没有把路径设置在C盘的话，部分功能就会失效(如显示助手)，这是什么原因呢？（已开启管理员权限）
2.除了打log的方式，还有其它实用的调试方法吗？
之前没接触过前端，但看了up这个项目挺感兴趣的就着手学习了下，虽然成功打开了devtools，但是发现有些地方断不下来，后面才知道devtools似乎只能调试“渲染进程”，而electron中的“主进程”没法用这种方式调试；
搜了些文章，找到一篇关于electron的调试贴，https://blog.csdn.net/weixin_38080573/article/details/105048111
但是实测之后又遇到了问题，目前处于卡壳的状态，想请教下up开发过程中是怎么调试的？谢谢
![e27b31f13cd3c483d39e60838f73a6e](https://user-images.githubusercontent.com/45645581/185783224-1acbb1e8-017e-4d75-9642-0afd7677d12b.png)

**Comment by Java-S12138** [comment]
第一个问题: 我自己的电脑换了其它的盘功能一样可以使用, 这个比较玄学, 可能是电脑的原因吧
第二个问题: 我一直都是log的调试方式, 因为主进程的代码比较少, log一下就能看出问题
