### ISSUE TITLE
貌似在win11系统下软件不适用

### ISSUE THREAD

**Issue by xxxxxy211** [Java-S12138/frank#88]
frank 版本：1.24.12.17 (2022/9/15)
Windows 11 专业版：22000.978
![image](https://user-images.githubusercontent.com/59924364/191158857-1a0e010b-e761-4b20-8bfa-3cdbfa272517.png)

**Comment by Java-S12138** [comment]
没有啊。我自己的电脑就是win11，你试一下 先开英雄联盟客户端。然后启动frank。需要右键管理员权限打开

**Comment by xxxxxy211** [comment]
我先打开联盟，然后用管理员权限打开frank成功了，感谢
