### ISSUE TITLE
我的战绩界面为空呀，搜索也搜索不到

### ISSUE THREAD

**Issue by NNanfeng** [Java-S12138/frank#91]
![image](https://user-images.githubusercontent.com/92158315/191901509-bfb0d2e3-7580-4f8b-ae12-da25d2083e1f.png)

**Comment by DemoorBug** [comment]
同样的问题，刚登陆上游戏，可以查看，过几秒后就会查不了战绩，以及其他功能均无法使用

**Comment by NNanfeng** [comment]
我在游戏大厅查看战绩的时候，提示服务器发生问题，可能是这个问题，看看之后会不会行吧

**Comment by Moac1129** [comment]
我也遇到了同样的问题，所以来这里看看是不是只有我才有这个问题....

**Comment by Java-S12138** [comment]
最新软件视频: https://www.bilibili.com/video/BV1XP4y1174C/
