### ISSUE TITLE
软件基本功能无法运转

### ISSUE THREAD

**Issue by Crany-web** [Java-S12138/frank#92]
2022-9-23软件无法自动接受对局，无法配置符文(重装还是无法解决问题)版本：1.24.1217

**Comment by iioSnail** [comment]
腾讯改了LCU接口调用方式，我看端口还能通，但是https调用收不到响应，最终超时

**Comment by cangzhang** [comment]
按照这里操作

https://github.com/cangzhang/champ-r/issues/215#issuecomment-1257224369

**Comment by Java-S12138** [comment]
> 按照这里操作
> 
> [cangzhang/champ-r#215 (comment)](https://github.com/cangzhang/champ-r/issues/215#issuecomment-1257224369)

感谢大佬分享的解决方案

**Comment by chickesSAMA** [comment]
登录体验服需要wegame开启但是没有体验服账号咋搞，官网也看不见体验服申请

**Comment by Moac1129** [comment]
已解决，感谢大佬 @cangzhang

**Comment by Java-S12138** [comment]
最新软件视频: https://www.bilibili.com/video/BV1XP4y1174C/
